# Site settings
title: Nils Kuhler CV 
description: Nils Kuhler CV
favicon: /assets/img/foto.jpg
baseurl: "https://nilskuhler.github.io/mygithub/"  # Use "" when running locally
url: "https://nilskuhler.github.io/mygithub/"      # Use "" when running locally
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Nils Kuhler
  title: Devops Data Engineer
  address: Amsterdam, The Netherlands
  email: Please use linked in for futher (contact of feedback) info
  link: https://nilskuhler.github.io/mygithub/
  weibo:
  github: nilskuhler
  linkedin: nilskuhler
  twitter: 
  gavatar: /resumecard/assets/img/foto.jpg
  stackoverflow:
#  stackoverflow: 4582127
# Issue: Could not find a quick solution to print a multiline text \n does not work /n
# jekyll 4.0.0 | Error:  (/srv/jekyll/_config.yml): could not find expected ':' while scanning a simple key at line
# I introduce the following -line solution  ...
# NK 11 oct Added Summary field. 
# Please add max 103 text.size string summary text on the - line: elements.
# Use empty lines "    - line:" for new lines. I could not find any way to use \n newlines in _config.yml files
# You cannot use a unicode character as the first character of an line sentence
# You cannot use : colon character in this *.yml file or in the summary text; use unicode "&#58;" for ":" colons 
# You cannot use > character in this *.yml file or in the summary text or unicode &gt or &#62;
# You cannot use a lot of other symbols that like -, ... all because they have a yml data function. 
# Space(s) on the beginning of the line are not displayed partly because liquid display processing
# _ are replaced by liquid display proces in html by " "
  summary:
    - line: I am working as an IT consultant since 1994 on ambitious/international large projects for fortune 500 
    - line: clients. I worked since 2008 worked for client Alliander and acted in different roles&#58;
    - line: Data Engineer, (Devops) Developer, System Adminstration and Business Analyst. At Alliander I worked 
    - line: in an environment with 150+ middleware Interfaces, applications and databases. As a team we were 
    - line: responsible for 24/7 critical processes and resources. I worked with Waterfall, Agile, Six Sigma, 
    - line:  Scrum and Kanban methodologies. 
    - line:     
    - line: To keep up to date in the ever changing IT world I (self) study often. Certifications aquired&#58;
    - line: _&#62;30%CISSP, Scrum, JAVA, Oracle DBA, MCSE + Internet, MS Developer, ...
    - line: Summary of accomplished 100+ (MOOC) Educations/certifications&#58;
    - line: _&#62;30% Data science(Hadoop Eco(Kafka, Hive...) , Data Visualisation, AI/ML/DL, ...)
    - line: _&#62;25% Programming(Java, Pyton, Scala, R, Web design, ...)
    - line: _&#62;20% IT(Security, Cloud, (Docker) Virtualization, Networking, ...)
    - line: _&#62;15% Soft Skills & Management(Scrum, Agile, Six Sigma Black Belt, ...)
    - line: _&#62;10% IT Architectuur(TOGAF, ...) & Wiskunde(Statistiek, ...)
    - line: 
    - line: My ambitions for the future as a data engineer are to work on data science/AI solutions in
    - line: collaboration with clients. Ideally I would like to work with the 
    - line: Apache Hadoop ecosystem (Hive, Kafka, ...) and Python.)
  workHistory:
    - work1:
      company: Ciber Consultancy - Client Alliander
      location:
      title: Senior Technical Consultant
      started: 2009
      duration: 2009 - 2019
      description: As an external Ciber consultant I have worked a decade+ a for our client Alliander(Dutch Energy company) on long term assignments for different Departments. Initially I started as a Developer, later I switched roles to Devops System Administration, Data Engineer, Business Analyst/IT Liasion. At Alliander I worked in an environment with 150+ middleware Interfaces, applications and databases.
    - work2:
      company: 
      location:
      title: Data Engineer
      started: 
      duration: 
      description: I provided Alliander with technical support for the reconciliation proces model. Alloc/Reconciliation is one of the critical 24/7 core processes in Alliander. Other taks were database performance tuning and database migration and phase outs, ETL(Extract Transform Load)/Data manipulation of critical proces data with Excel, Notepad++, Oracle Loader, PL SQL, custom scripting, proof of concept van Apache Hadoop en Cassandra Database Model in de Amazon Cloud.
    - work3:
      company: 
      location:
      title: Business Analyst/IT Liasion
      started: 
      duration: 
      description: I worked on CARS (Centraal aansluitingen register) and SOW (Stroomopwaarts) projects. CARS & SOW haven been very large projects(many partipants/parties involved) in the Dutch energy sector. I was resonsible for the contact with external parties EDSN, TENNET, AS1&AS2 parties concerning security and technical communication matters. I have been responsible for Q&A(like testing Acceptance Criteria) of deliverables, documentation, CMDB, Technical standards. Drafting Security guidelines. I was responsible for contacts with external relations with EDSN, AS1&AS2 parties, TENNET.
    - work4:
      company: 
      location:
      title: Development, Devops System Administration
      started: 
      duration: 
      description: I worked in maintenance and DEVOPS development on Oracle Weblogic Service Bus, linux, python, java, scala, tomcat web apps and databases. I have implemented security guidlines. My tasks also included 24/7 monitoring tasks using (customizable) tooling like nagios and solving (critical) incidents.
    - work5:
      company: Ciber Consultancy
      location:
      title: Senior (Technical) Consultant
      started: 2004
      duration: 2004 - 2009
      description: I have worked as Developer, Designer, Test coordination for the following clients RGD, CIZ, Wereld Omroep as Senior Technical Consultant.
    - work6:
      company: Hewlett Packard Consultancy
      location:
      title: (Technical) Consultant
      started: 2000
      duration: 2000 - 2004
      description: I have worked as a Developer, Designer, Security Specialist. I developed in C(++), Microsoft solutions and Java. I worked for clients KPN, ABN Amro and Toyota. For Toyota I worked on the implementation of a SSO security portal.
    - work7:
      company: Cambrigde Technology Partners Consultancy
      location:
      title: Senior (Technical) Consultant
      started: 1996
      duration: 1996 - 2000
      description: I worked for clients Vrij Uit, HP, Philips, Interpay, Viag Interkom, Libertel, Achmea, Gerling. For Philips I worked on a large oracle data migrition project. Technologies used&#58; Java, Unix, C++, Oracle PL SQL and Python.
  educationHistory:
    - education1:
      organization: Contact me for a complete (100+) list of completed self study MOOC courses on Coursera certifications !!!
      location: 
      degree: 
      major: 
      started: 2019
      duration: (1997 - now)
      description: I have completed 100+ self study courses. Certifications acquired among other things &#58; CISSP, Scrum, JAVA (Architect), Oracle DBA, MCSE + Internet, MS Developer, ... 
    - education2:
      organization: Online Mooc courses on Coursera by Stanford, Johns Hopkins, Vanderbilt, ...
      location: 
      degree: 
      major: 
      started: 2005
      duration: (2005 - now)
      description: I have completed 50+ online courses among which&#58; Cloud Computing, (R) Data Science(Statistical,Interference, Developing Data Products, Data Analysis, Machine Learning, Regression, Models, Reproducible Research), Data mining, Java, Scala, Android, Machine Learning (by Andrew NG)
    - education3: 
      organization: Professional courses
      location: 
      degree: 
      major: 
      started: 
      duration: (1995 - Now)
      description: Consultancy Skills Scrum Master Trained+ Certified, Axway System Management API, Programming Spring Workshop 2006, ITIL Foundations, Oracle Weblogic J2EE,Effective Facilitation Skills, Presentation Skills, Communication Skills, Negotiation Skills, Advisory Skills, Project Management Prince 2
    - education4: 
      organization: MBA - Univeristy Nice/Stanford 
      location: Nice France
      degree: 
      major: 
      started: 1995
      duration: (1994 - 1995)
      description: finished 90% first year
    - education6: 
      organization: Master Management Information Systems - Universiteit van Amsterdam
      location: 
      degree: 
      major: 
      started: 1990
      duration: (1990 - 1994)
      description: Dutch translation - (DRS Bestuurlijke informatica)  
    - education7:  
      organization: Hava/VWO - Secondary school - Waterlant College
      location: 
      degree: 
      major: 
      started: 
      duration: (1981 - 1989)
      description:	  
  languages:
    - language1:
      name: Dutch
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
    - language3:
      name: French
      proficiency: Intermediate
    - language4:
      name: German
      proficiency: Basic
  programmingSkills:
    - skill1:
      name: Communication/Team Work
      percentage: 80%
    - skill2: 
      name: Management - Scrum, Kanban, 6 Sigma - Black Belt
      percentage: 75%      
    - skill2:
      name: Data Science (Visualisation, Modeling, ETL)
      percentage: 70%
    - skill3:
      name: Programming - Java, Python, HTML, Jscript, ...
      percentage: 80%
    - skill4:
      name: Programming - Scala, Ruby, C(++), Android other
      percentage: 70%
    - skill3:
      name: Data Science
      percentage: 70%
    - skill6:
      name: Data Science (ML, DL, AI)
      percentage: 50%
      
      
      
      
      