# Site settings
title: Nils Kuhler CV 
description: Nils Kuhler CV
favicon: /assets/img/favicon.jpg
locationJPG: /assets/img/020_fix.jpg
# OR>>Uncomment baseurl and url settings when deploying to github/remotely
baseurl: "https://nilskuhler.github.io/resumecard/"  
url: "https://nilskuhler.github.io/resumecard/"      
# OR>>Uncomment baseurl and url settings when running locally. baseurl and url need to be ""
##baseurl: ""                                        # Use above setting when running remotely
##url: ""                                            # Use above setting when running remotely
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Nils Kuhler
  title: Data Sciene Engineer/Business Analist
  address: Amsterdam, The Netherlands
  email: Please use linked in for further (contact of feedback) info
  linkedin: nilskuhler
  link: https://nilskuhler.github.io/mygithub/
  link: https://nilskuhler.github.io/Blog/course/
# weibo:
  github: nilskuhler
# twitter: 
  gavatar: /resumecard/assets/img/foto.jpg
# stackoverflow:
#  stackoverflow: 4582127
# NK 11 oct Added Summary field. 
# Issue: Could not find a quick solution to print a multiline text \n does not work /n in -line or text fields
# jekyll 4.0.0 | Error:  (/srv/jekyll/_config.yml): could not find expected ':' while scanning a simple key at line
# I haved introduce the following -line concept  ... it is not yet perfect
# Space(s) on the beginning of the line are not displayed partly because liquid display processsing
# _ are replaced by summary field liquid display function logic in the index.html by " "
# Please note that max line lenght in this function is hardcoded to 400 characters.  " 
# Please note that approx. max 103 text.size string summary text fit on the - line: elements. 
# I have not yet determined all constraints on characters to be used in this yaml. 
# Check comments underneeth... for more info on constraints. 
# Use empty lines "    - line:" for new lines. I could not find any way to use \n newlines in _config.yml files
# You cannot use a unicode character as the first character of an line sentence
# You cannot use : colon character in this *.yml file or in the summary text; use unicode "&#58;" for ":" colons 
# You cannot use > character in this *.yml file or in the summary text or unicode &gt or &#62;
# You cannot use a lot of other symbols that like -, ... all because they have a yml data function. 
  summary:
    - line:
    - line: Nils is an experienced IT consultant with a proven track record since 1994, successfully delivering large scale,
    - line: ambitious, and international projects for Fortune 500 clients. His experience includes&#58;
    - line: _&#62; Roles&#58; Data Engineer, Data Analyst, DevOps Developer, System Administrator, and Business Analyst
    - line: _&#62; Expertise in managing complex IT landscapes with 150+ middleware interfaces, applications, and databases
    - line: _&#62; Ensuring 24/7 availability of critical processes and resources as part of a high-performing team
    - line: _&#62; Proficiency in Waterfall, Agile, Six Sigma, Scrum, and Kanban methodologies
    - line:     
    - line: Committed to continuous learning, having completed numerous self-studies and certifications&#58;
    - line: _&#62; CISSP, Scrum, JAVA, Oracle DBA, MCSE + Internet, MS Developer, ...
    - line: Summary of accomplished 100+ Educations/certifications&#58;
    - line: _&#62; Data science(Hadoop Eco(Kafka, Hive...) , Data Visualization, (Gen)AI/ML/DL, ...)
    - line: _&#62; Programming(Java, Python, Scala, R, Web design, ...)
    - line: _&#62; IT(Security, Cloud, (Docker) Virtualization, Networking, ...)
    - line: _&#62; Soft Skills & Management(Scrum, Agile, Six Sigma Black Belt, ...)
    - line: _&#62; IT Architecture(Java Architect, ...) & Mathematics(Statistics, ...)
    - line: 
    - line:  Now seeking to leverage my expertise in Data Science, Machine Learning (ML), Deep Learning (DL), and Generative AI (GenAI) for impactful projects.
  workHistory:
    - work2:
      company: Experis Consultancy(known as Ciber before acquisition in 2016) - Client Alliander
      location: Zutphen, Haarlem, Amsterdam, Hilversum, Den Hague, Eindhoven, Nieuwegein, Schiphol
      title: Senior Technical Consultant
      started: 2005
      duration: 2005 - 2019  
      description: Most recently Nils worked as a Data Engineer/Analist for several dutch government agencies(RIVM, RVIG, UWV). Before he has worked a decade+ a for client Alliander(Dutch Energy company) on long term assignments for different departments. For Alliander he initially started as a Developer, later switched roles to Devops System Administrator, Data Engineer, Business Analyst/IT Liaison. At Alliander I worked in an environment with 150+ middleware Interfaces, applications and databases. Worked as Developer, Designer, Test coordination for the following clients RGD, CIZ, Wereld Omroep, Nuon.
    - work3:
      company: Alliander
      location:
      title: Consultant - Data Engineer
      started: 
      duration: 2017
      description: Nils provided Alliander with technical and business support for the reconciliation process model. Alloc/Reconciliation is one of the critical 24/7 core processses in Alliander. Other tasks were database performance tuning, migration, phase outs, ETL(Extract Transform Load)/Data manipulation of critical process data with Excel, Notepad++, Oracle Loader, PL SQL, custom scripting). I participated proof of concept project with Apache Hadoop and Cassandra Database in the Amazon Cloud.
    - work4:
      company: Alliander
      location:
      title: Consultant - Business Analyst/IT Liaison
      started: 
      duration: 2012
      description: Nils worked on CARS (Centraal aansluitingen register) and SOW(Stroomopwaarts) projects. CARS & SOW haven been very large projects(many partipants/parties involved) in the Dutch energy sector. Nils was responsible for&#58; AS1 en AS2 security and technical communication, the contact with external parties (EDSN, TENNET, AS1&AS2), Q&A(e.g. testing Acceptance Criteria) of deliverables, documentation, CMDB, Technical standards and drafting Security guidelines.
    - work5:
      company: Alliander
      location:
      title: Consultant Developer, Devops System Administrator
      started: 2008
      duration: 
      description: Nils worked in maintenance and DEVOPS development on Oracle Weblogic Service Bus, linux, Python, java, scala, tomcat web apps and databases. Nils has implemented security guidelines. Other tasks also included 24/7 monitoring tasks using (customizable) tooling like Nagios and solving (critical) incidents.
    - work7:
      company: Hewlett Packard Consultancy
      location: Amstelveen, Utrecht, Brussels - Belgium
      title: (Technical) Consultant
      started: 2000
      duration: 2000 - 2004
      description: Worked as a Developer, Designer, Security Specialist. I developed in C(++), Microsoft solutions and Java. I worked for clients KPN, ABN Amro and Toyota. For Toyota worked on the implementation of a SSO security portal.
    - work8:
      company: Cambrigde Technology Partners Consultancy
      location: Frankfurt, Vienna, Amsterdam, Utrecht, Maastricht, Woerden
      title: Senior (Technical) Consultant
      started: 1995
      duration: 1995 - 2000
      description: Worked for clients Vrij Uit, HP, Philips, Interpay, Viag Interkom, Libertel, Achmea, Gerling. For Philips worked on a large oracle data migrition project. Technologies used&#58; Java, Unix, C++, Oracle PL SQL and Python.
    - work9:
      company: FDM Pharma
      location: Sopia Antipolis, France
      title: DBA
      started: 1995
      duration: 1994 - 1995
      description: Worked as DBA
  educationHistory:
    - education1:
      organization: Courses & Certifications&#58; For a complete courses and certifications overview click above github course link in CV header
      location: 
      degree: 
      major: 
      started: 2025
      duration: 1997 - now
      description: Completed 100+ courses & certifications. Certifications acquired among which&#58; CISSP, Scrum, Java (Architect), Oracle DBA, MCSE + Internet, MS Developer, ... 
    - education2:
      organization: Professional courses
      location: 
      degree: 
      major: 
      started: 2025
      duration: 1997 - now
      description: Completed 50+ online (self study) courses from Coursera by Stanford, Johns Hopkins, Vanderbilt, ... among which&#58; Cloud Computing, (R) Data Science(Statistical, Interference, Developing Data Products, Data Analysis, Machine Learning, Regression, Models, Reproducible Research), Data mining, Java, Scala, Android, Machine Learning (by Andrew NG)
    - education3: 
      organization: Online Courses
      location: 
      degree: 
      major: 
      started: 
      duration: 1995 - Now
      description: Consultancy Skills Scrum Master Trained+ Certified, Axway System Management API, Programming Spring Workshop 2006, ITIL Foundations, Oracle Weblogic J2EE,Effective Facilitation Skills, Presentation Skills, Communication Skills, Negotiation Skills, Advisory Skills, Project Management Prince 2
    - education4: 
      organization: MBA - University Nice/Stanford 
      location: Nice France/Stanford USA
      degree: 
      major: 
      started: 1994
      duration: 1994 - 1995
      description: finished 90% first year
    - education6: 
      organization: Master Management Information Systems - Universiteit van Amsterdam
      location: Amsterdam
      degree: 
      major: 
      started: 1990
      duration: 1990 - 1994
      description: Dutch translation - (DRS Bestuurlijke informatica)  
    - education7:  
      organization: Havo/VWO - Secondary school - Waterlant College
      location: Amsterdam
      degree: 
      major: 
      started: 1981
      duration: 1981 - 1989
      description:	  
  languages:
    - language1:
      name: Dutch
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
    - language3:
      name: French
      proficiency: Intermediate
    - language4:
      name: German
      proficiency: Basic
  programmingSkills:
    - skill1:
      name: Communication/Team Work
      percentage: 80%
    - skill2: 
      name: Management - Scrum, Kanban, 6 Sigma - Black Belt
      percentage: 70%      
    - skill2:
      name: Data Science (Visualisation, Modeling, ETL)
      percentage: 70%
    - skill3:
      name: Programming - Java, Python, HTML, Jscript, ...
      percentage: 80%
    - skill4:
      name: Programming - Scala, Ruby, C(++), Android, other
      percentage: 70%
    - skill3:
      name: Databases(DBA, Oracle, SQL, NOSQL)
      percentage: 70%
    - skill6:
      name: Data Science (ML, DL, AI, GenAI)
      percentage: 60%
      
      
      
      
      
