# Site settings
title: Nils Kuhler CV 
description: Nils Kuhler CV
favicon: /assets/img/favicon.jpg
locationJPG: /assets/img/020_fix.jpg
# OR>>Uncomment baseurl and url settings when deploying to github/remotely
baseurl: "https://nilskuhler.github.io/resumecard/"  
url: "https://nilskuhler.github.io/resumecard/"      
# OR>>Uncomment baseurl and url settings when running locally. baseurl and url need to be ""
##baseurl: ""                                        # Use above setting when running remotely
##url: ""                                            # Use above setting when running remotely
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Nils Kuhler
  title: Data Sciene Engineer/Business Analist
  address: Amsterdam, The Netherlands
  email: Please use linked in for further (contact of feedback) info
  linkedin: nilskuhler
  link: https://nilskuhler.github.io/mygithub/
  link: https://nilskuhler.github.io/Blog/course/
# weibo:
  github: nilskuhler
# twitter: 
  gavatar: /resumecard/assets/img/foto.jpg
# stackoverflow:
#  stackoverflow: 4582127
# NK 11 oct Added Summary field. 
# Issue: Could not find a quick solution to print a multiline text \n does not work /n in -line or text fields
# jekyll 4.0.0 | Error:  (/srv/jekyll/_config.yml): could not find expected ':' while scanning a simple key at line
# I haved introduce the following -line concept  ... it is not yet perfect
# Space(s) on the beginning of the line are not displayed partly because liquid display processsing
# _ are replaced by summary field liquid display function logic in the index.html by " "
# Please note that max line lenght in this function is hardcoded to 400 characters.  " 
# Please note that approx. max 103 text.size string summary text fit on the - line: elements. 
# I have not yet determined all constraints on characters to be used in this yaml. 
# Check comments underneeth... for more info on constraints. 
# Use empty lines "    - line:" for new lines. I could not find any way to use \n newlines in _config.yml files
# You cannot use a unicode character as the first character of an line sentence
# You cannot use : colon character in this *.yml file or in the summary text; use unicode "&#58;" for ":" colons 
# You cannot use > character in this *.yml file or in the summary text or unicode &gt or &#62;
# You cannot use a lot of other symbols that like -, ... all because they have a yml data function. 
  summary:
    - line:
    - line: Nils is an experienced IT consultant with a proven track record since 1994, successfully delivering large scale,
    - line: ambitious, and international projects for Fortune 500 clients. His experience includes&#58;
    - line: _&#62; Roles&#58; Data Engineer, Data Analyst, DevOps Developer, System Administrator, and Business Analyst
    - line: _&#62; Expertise in managing complex IT landscapes with 150+ middleware interfaces, applications, and databases
    - line: _&#62; Ensuring 24/7 availability of critical processes and resources as part of a high-performing team
    - line: _&#62; Proficiency in Waterfall, Agile, Six Sigma, Scrum, and Kanban methodologies
    - line:     
    - line: Committed to continuous learning, having completed numerous self-studies and certifications&#58;
    - line: _&#62; CISSP, Scrum, JAVA, Oracle DBA, MCSE + Internet, MS Developer, ...
    - line: Summary of accomplished 100+ Educations/certifications&#58;
    - line: _&#62; Data science(Hadoop Eco(Kafka, Hive...) , Data Visualization, (Gen)AI/ML/DL, ...)
    - line: _&#62; Programming(Java, Python, Scala, R, Web design, ...)
    - line: _&#62; IT(Security, Cloud, (Docker) Virtualization, Networking, ...)
    - line: _&#62; Soft Skills & Management(Scrum, Agile, Six Sigma Black Belt, ...)
    - line: _&#62; IT Architecture(Java Architect, ...) & Mathematics(Statistics, ...)
    - line: 
    - line:  Now seeking to leverage my expertise in Data Science, Machine Learning (ML), Deep Learning (DL), and Generative AI (GenAI) for impactful projects.
  workHistory:
    - work1:
      company: 2Experis Consultancy(known as Ciber before acquisition in 2016)
      location: Zutphen, Haarlem, Amsterdam, Hilversum, Den Hague, Eindhoven, Nieuwegein, Schiphol
      title: Senior Technical Consultant
      started: 2005
      duration: 2005 - Now  
      description: Most recently, Nils worked as a Data Engineer and Data Analyst for several Dutch government agencies, including RIVM, RVIG, and UWV. Prior to that, he spent over a decade at Alliander (a Dutch energy company) on long-term assignments across various departments. He initially joined Alliander as a Developer before transitioning into roles such as DevOps System Administrator, Data Engineer, and Business Analyst/IT Liaison. At Alliander, he operated in a complex IT environment with 150+ middleware interfaces, applications, and databases. Additionally, he has worked as a Developer, Designer, and Test Coordinator for clients such as RGD, CIZ, Wereld Omroep, and Nuon.
    - work3:
      company: Alliander1
      location:
      title: Consultant - Data Engineer
      started: 2017
      duration: 2017 - 2019
      description: Nils provided technical and business support to Alliander the reconciliation (critical,24/7) core process within the company. His responsibilities included database performance tuning, migrations, system phase-outs, and ETL (Extract, Transform, Load) processes. He worked extensively on data manipulation for critical processes using Excel, Notepad++, Oracle Loader, PL/SQL, and custom scripting. Additionally, he participated in a proof-of-concept project utilizing Apache Hadoop and Cassandra Database in the Amazon Cloud.
    - work4:
      company: Alliander
      location:
      title: Consultant - Business Analyst/IT Liaison
      started: 2013
      duration: 2013 - 2017
      description: Nils worked on the CARS (Centraal Aansluitingen Register) and SOW (Stroomopwaarts) projects, both of which were large-scale initiatives in the Dutch energy sector involving multiple stakeholders. He was responsible for AS1 and AS2 security and technical communication. Serving as the point of contact for external parties, including EDSN, TENNET, and AS1/AS2 partners. Q&A of deliverables, including testing against acceptance criteria, Documentation management, CMDB maintenance, and ensuring compliance with technical standards. Drafting security guidelines to enhance system integrity and regulatory compliance.
    - work5:
      company: NUON & Alliander - Initially worked for NUON, which demerged into NUON and Alliander in 2009, and continued working for Alliander thereafter.
      location:
      title: Consultant Developer, Devops System Administrator
      started: 2008
      duration: 2008 - 2013
      description: Nils initially worked in DevOps development, completing key deliverables before transitioning to system administration after two years. He worked with technologies such as Oracle WebLogic Service Bus, Linux, Python, Java, Scala, Tomcat web applications, and databases. He also implemented security guidelines to enhance system integrity. His additional responsibilities included 24/7 monitoring using customizable tools like Nagios, as well as troubleshooting and resolving critical incidents.
    - work6:
      company: Hewlett Packard Consultancy
      location: Amstelveen, Utrecht, Brussels - Belgium
      title: (Technical) Consultant
      started: 2000
      duration: 2000 - 2004
      description: Worked as a Developer, Designer, Security Specialist. Developed in C(++), Microsoft solutions and Java. Worked for clients KPN, ABN Amro and Toyota. For Toyota worked on the implementation of a SSO security portal.
    - work7:
      company: Cambrigde Technology Partners Consultancy
      location: Frankfurt, Vienna, Amsterdam, Utrecht, Maastricht, Woerden
      title: Senior (Technical) Consultant
      started: 1995
      duration: 1995 - 2000
      description: Worked for clients Vrij Uit, HP, Philips, Interpay, Viag Interkom, Libertel, Achmea, Gerling. For Philips worked on a large oracle data migrition project. Technologies used&#58; Java, Unix, C++, Oracle PL SQL and Python.
    - work8:
      company: FDM Pharma
      location: Sopia Antipolis, France
      title: DBA
      started: 1994
      duration: 1994 - 1995
      description: Worked as DBA
  educationHistory:
    - education1:
      organization: Courses & Certifications&#58; For a complete courses and certifications overview click above github course link in CV header
      location: 
      degree: 
      major: 
      started: 2025
      duration: 1997 - now
      description: Completed 100+ courses & certifications. Certifications acquired among which&#58; CISSP, Scrum, Java (Architect), Oracle DBA, MCSE + Internet, MS Developer, ... 
    - education2:
      organization: Professional courses
      location: 
      degree: 
      major: 
      started: 2025
      duration: 1997 - now
      description: Completed 50+ online (self study) courses from Coursera by Stanford, Johns Hopkins, Vanderbilt, ... among which&#58; Cloud Computing, (R) Data Science(Statistical, Interference, Developing Data Products, Data Analysis, Machine Learning, Regression, Models, Reproducible Research), Data mining, Java, Scala, Android, Machine Learning (by Andrew NG)
    - education3: 
      organization: Online Courses
      location: 
      degree: 
      major: 
      started: 
      duration: 1995 - Now
      description: Consultancy Skills Scrum Master Trained+ Certified, Axway System Management API, Programming Spring Workshop 2006, ITIL Foundations, Oracle Weblogic J2EE,Effective Facilitation Skills, Presentation Skills, Communication Skills, Negotiation Skills, Advisory Skills, Project Management Prince 2
    - education4: 
      organization: MBA - University Nice/Stanford 
      location: Nice France/Stanford USA
      degree: 
      major: 
      started: 1994
      duration: 1994 - 1995
      description: finished 90% first year
    - education6: 
      organization: Master Management Information Systems - Universiteit van Amsterdam
      location: Amsterdam
      degree: 
      major: 
      started: 1990
      duration: 1990 - 1994
      description: Dutch translation - (DRS Bestuurlijke informatica)  
    - education7:  
      organization: Havo/VWO - Secondary school - Waterlant College
      location: Amsterdam
      degree: 
      major: 
      started: 1981
      duration: 1981 - 1989
      description:	  
  languages:
    - language1:
      name: Dutch
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
    - language3:
      name: French
      proficiency: Intermediate
    - language4:
      name: German
      proficiency: Basic
  programmingSkills:
    - skill1:
      name: Communication/Team Work
      percentage: 80%
    - skill2: 
      name: Management - Scrum, Kanban, 6 Sigma - Black Belt
      percentage: 70%      
    - skill2:
      name: Data Science (Visualisation, Modeling, ETL)
      percentage: 70%
    - skill3:
      name: Programming - Java, Python, HTML, Jscript, ...
      percentage: 80%
    - skill4:
      name: Programming - Scala, Ruby, C(++), Android, other
      percentage: 70%
    - skill3:
      name: Databases(DBA, Oracle, SQL, NOSQL)
      percentage: 70%
    - skill6:
      name: Data Science (ML, DL, AI, GenAI)
      percentage: 60%
      
      
      
      
      
